# Generated by Django 4.1.1 on 2022-09-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pegawai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pegawai', models.CharField(max_length=50)),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'laki-laki'), ('Prempuan', 'prempuan')], max_length=10)),
            ],
        ),
    ]
