# Generated by Django 4.1.1 on 2022-09-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pegawai',
            options={'verbose_name_plural': 'Pegawai'},
        ),
        migrations.CreateModel(
            name='report_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tujuan', models.CharField(max_length=200)),
                ('pinjam_alat', models.CharField(max_length=100)),
                ('id_pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pegawai')),
            ],
            options={
                'verbose_name_plural': 'Report in',
            },
        ),
    ]
