# Generated by Django 4.1.1 on 2022-09-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pegawai_options_report_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_in',
            name='id_pegawai',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.pegawai'),
        ),
    ]
