# Generated by Django 4.1.1 on 2022-09-19 09:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_report_in_id_pegawai'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_in',
            name='tanggal_masuk',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='report_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_keluar', models.DateField(auto_now_add=True)),
                ('pegawai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.report_in')),
            ],
            options={
                'verbose_name_plural': 'Report out',
            },
        ),
    ]
