# Generated by Django 4.1.1 on 2022-09-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_report_in_tanggal_masuk_report_out'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_out',
            old_name='pegawai',
            new_name='id_pegawai',
        ),
    ]
