# Generated by Django 4.1.1 on 2022-09-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_report_out_id_pegawai_report_out_id_pegawai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_out',
            name='id_pegawai',
        ),
        migrations.AddField(
            model_name='report_out',
            name='data_peminjam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.report_in'),
        ),
        migrations.AlterField(
            model_name='report_in',
            name='id_pegawai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pegawai'),
        ),
    ]
