# Generated by Django 4.1.1 on 2022-09-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_report_out_id_pegawai_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_out',
            name='tanggal_keluar',
            field=models.DateField(auto_now=True),
        ),
    ]
