# Generated by Django 4.1.1 on 2022-09-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_report_out_tanggal_keluar'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=200)),
                ('jumlah', models.IntegerField()),
                ('tanggal_ditambah', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='report_in',
            name='pinjam_alat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.data_barang'),
        ),
    ]
