# Generated by Django 4.1.1 on 2022-09-30 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_data_barang_alter_report_in_pinjam_alat'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_dokumen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=200)),
                ('jenis_dokumen', models.CharField(max_length=200)),
                ('tanggal_ditambah', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Data Barang',
            },
        ),
        migrations.CreateModel(
            name='masuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan', models.CharField(max_length=200)),
                ('tanggal_masuk', models.DateField(auto_now_add=True)),
                ('jam_masuk', models.TimeField(auto_now_add=True)),
                ('id_pegawai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pegawai')),
                ('pinjam_alat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.data_dokumen')),
            ],
            options={
                'verbose_name_plural': 'Report in',
            },
        ),
        migrations.RemoveField(
            model_name='report_in',
            name='id_pegawai',
        ),
        migrations.RemoveField(
            model_name='report_in',
            name='pinjam_alat',
        ),
        migrations.RenameModel(
            old_name='report_out',
            new_name='keluar',
        ),
        migrations.DeleteModel(
            name='data_barang',
        ),
        migrations.DeleteModel(
            name='report_in',
        ),
        migrations.AlterField(
            model_name='keluar',
            name='data_peminjam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.masuk'),
        ),
    ]
