# Generated by Django 4.1.1 on 2022-09-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_data_dokumen_masuk_remove_report_in_id_pegawai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data_dokumen',
            options={'verbose_name_plural': 'Data dokumen'},
        ),
        migrations.AlterModelOptions(
            name='keluar',
            options={'verbose_name_plural': 'Data keluar'},
        ),
        migrations.AlterModelOptions(
            name='masuk',
            options={'verbose_name_plural': 'Data masuk'},
        ),
    ]
