# Generated by Django 4.1.1 on 2022-09-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_pinjam_alat_masuk_pinjam_dokumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masuk',
            name='jam_masuk',
            field=models.TimeField(),
        ),
    ]
