# Generated by Django 4.1.1 on 2022-09-30 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_masuk_jam_masuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_dokumen',
            name='tanggal_ditambah',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='keluar',
            name='tanggal_keluar',
            field=models.DateField(auto_now_add=True),
        ),
    ]
