# Generated by Django 4.1.1 on 2022-09-30 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_data_dokumen_tanggal_ditambah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_dokumen',
            name='tanggal_ditambah',
            field=models.DateField(),
        ),
    ]
