# Generated by Django 4.1.1 on 2022-09-30 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_data_dokumen_tanggal_ditambah'),
    ]

    operations = [
        migrations.AddField(
            model_name='keluar',
            name='jam_keluar',
            field=models.TimeField(default=datetime.datetime(2022, 9, 30, 2, 55, 48, 751073, tzinfo=datetime.timezone.utc)),
        ),
    ]
