# Generated by Django 4.1.1 on 2023-12-21 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_keluar_jam_keluar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keluar',
            options={'verbose_name_plural': 'Data keluar Ruangan'},
        ),
        migrations.AlterModelOptions(
            name='masuk',
            options={'verbose_name_plural': 'Data masuk Ruangan'},
        ),
        migrations.AddField(
            model_name='data_dokumen',
            name='jumlah_exemplar',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
